apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"   # apply before kube-prometheus-stack
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://github.com/cmamith/gitops-apps
    targetRevision: main
    path: observability
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
