apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "65.0.0"
      helm:
        valueFiles:
          - $values/observability/kube-prometheus/values/base.yaml
    - repoURL: https://github.com/your-org/gitops-apps
      targetRevision: main
      path: observability/alerts
      directory:
        recurse: true
      # optional: kustomize build the alerts folder instead of raw yamls
      # kustomize: {}
    - repoURL: https://github.com/your-org/gitops-apps
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
