apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-cloudwatch
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-for-fluent-bit
    targetRevision: 0.1.28
    helm:
      values: |
        serviceAccount:
          create: true
          name: fluent-bit
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::177206615793:role/eks-fluentbit-cloudwatch

        namespaceOverride: logging
        daemonSet:
          enabled: true

        # Use chart-managed CloudWatch Logs output
        cloudWatch:
          enabled: false
        cloudWatchLogs:
          enabled: true
          region: ap-southeast-1
          logGroupName: /eks/3tier/fallback   # use the template below
          logGroupTemplate: /eks/3tier/$kubernetes['namespace_name']/$kubernetes['labels']['svc']-$kubernetes['container_name']
          logStreamTemplate: ${kubernetes['pod_name']}.${kubernetes['container_name']}
          autoCreateGroup: true
          logRetentionDays: 14

        # Inputs / filters by the chart
        filters:
          kubernetes:
            enabled: true
            match: "*"
            kubeURL: https://kubernetes.default.svc

        input:
          tail:
            enabled: true
            path: /var/log/containers/*.log
            parser: docker

        resources:
          requests: { cpu: 25m, memory: 96Mi }
          limits:   { cpu: 150m, memory: 192Mi }

        tolerations:
          - operator: Exists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
