apiVersion:  external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager     # <-- match your actual store name
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana/admin        # AWS Secrets Manager secret name
        property: adminUser
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin
        property: adminPassword