apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin
  namespace: dev-tools
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: jenkins-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: dev/jenkins/admin_credentials
        property: username
    - secretKey: password
      remoteRef:
        key: dev/jenkins/admin_credentials
        property: password
